### ISSUE TITLE
Peercoin transaction parsing workflow is akward.

### ISSUE THREAD

**Issue by peerchemist** [PeerAssets/btcpy#10]
I believe `btcpy.structs.transaction.PeercoinTx` can presume some parameters. Right now workflow is too complicated.

Try the following:
```
provider = pa.Explorer(network='tppc')
raw = provider.getrawtransaction('c418f3bded92ebc035cfefc93f54dc8a501702e6ad4e6a26a07aab87f4cfb653')

transaction = PeercoinTx.unhexlify(raw)
```

`unhexlify` fails as it uses default BitcoinMainnet tx_parser.

let's try something different:

```
transaction = PeercoinTx.unhexlify(raw, network=network_params)
```

Fails again, still using BitcoinMainnet tx_parser.

PeercoinTx.unhexlify method should automatically use Peercoin network_params and Peercoin tx_parser.

**Comment by belovachap** [comment]
sounds pretty reasonable, i'll fiddle with it :+1:
