### ISSUE TITLE
Use HMAC-SHA512 for Kutil

### ISSUE THREAD

**Issue by saeveritt** [PeerAssets/btcpy#13]
For Kutil when generating from string seed.
https://gist.github.com/sipa/1799467#file-gistfile1-txt-L97-L104
https://tools.ietf.org/rfc/rfc4231.txt

Right now Kutil uses a single sha256 hash.
https://github.com/PeerAssets/pypeerassets/blob/master/pypeerassets/kutil.py#L34-L35

**Comment by peerchemist** [comment]
Wrong repo.
